
stages:
  - checks
  - publish

black:
  stage: checks
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --verbose -- .
  tags:
    - docker

tests:
  stage: checks
  image: "registry.forgemia.inra.fr/jbleger/docker-image-pandas-torch-sphinx:master"
  script:
    - pip install -r requirements.txt
    - cd tests
    - pip install -r requirements.txt
    - pytest

pages:
  stage: publish
  image: "registry.forgemia.inra.fr/jbleger/docker-image-pandas-torch-sphinx:master"
  script:
    - pip install -r requirements.txt
    - make -C docs html
    - rm -rf public/
    - cp -r docs/build/html public
  artifacts:
    paths:
      - public
  tags:
    - docker
  only:
    - main

publish_package:
  stage: publish
  image: "python:3.9"
  script:
    - pip install twine
    - python setup.py bdist_wheel
    - TWINE_PASSWORD=${TWINE_PASSWORD} TWINE_USERNAME=${TWINE_USERNAME} python -m twine upload dist/*
  tags:
    - docker
  only:
    - tags
