
stages:
  - checks
  - publish

black:
  stage: checks
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --verbose -- .
  tags:
    - docker


pages:
  stage: publish
  image: "registry.forgemia.inra.fr/jbleger/docker-image-jax-torch-sphinx:master"
  script:
    - make -C docs html
    - rm -rf public/
    - cp -r doc/build/html public
  artifacts:
    paths:
      - public
  tags:
    - docker
  only:
    - main
