
stages:
  - checks
  - publish

black:
  stage: checks
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --verbose -- .
  tags:
    - docker

tests:
  stage: checks
  image: "registry.forgemia.inra.fr/jbleger/docker-image-pandas-torch-sphinx:master"
  script:
    - pip install -r requirements.txt
    - pip install pytest-lazy-fixture
    - cd tests
    - pytest

pages:
  stage: publish
  image: "registry.forgemia.inra.fr/jbleger/docker-image-pandas-torch-sphinx:master"
  script:
    - pip install -r requirements.txt
    - make -C docs html
    - rm -rf public/
    - cp -r docs/build/html public
  artifacts:
    paths:
      - public
  tags:
    - docker
  only:
    - main
